nts=2^15-26;
jacobi1r=zeros(nts,nts);
jacobi1i=zeros(nts,nts);
jacobi2r=zeros(nts,nts);
jacobi2i=zeros(nts,nts);
jocabi1r=textread('jacobi1r.txt');
jocabi1i=textread('jacobi1i.txt');
jocabi2r=textread('jacobi2r.txt');
jocabi2i=textread('jacobi2i.txt');
jacobi1=zeros(nts,nts);
jacobi2=zeros(nts,nts);
jacobi1=jacobi1r+1i*jacobi1i;
jacobi2=jacobi2r+1i*jacobi2i;
size(jacobi1)
size(jacobi2)
tol=1e-12;
tR=500;
mR=500;
[U1,V1]=lowrank(jacobi1,tol,tR,mR);
[U2,V2]=lowrank(jacobi2,tol,tR,mR);
rank1=size(U1,2)
rank2=size(U2,2)
